/* Generated By:JavaCC: Do not edit this line. eje1Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface eje1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LINEA = 1;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<LINEA>",
  };

}
